Adds League SEA regions
bcho04/galeforce pull request #24
Opened 2023-01-10 14:13 UTC by xEcEz

2023-01-10 22:50 UTC, bcho04 requested changes
Thanks for the pull request! Would it be possible for you to set the target branch to `develop` rather than `master`?

2023-01-10 22:50 UTC, bcho04 commented on src/riot-api/enums/regions.ts
> +    PHILLIPINES = 'ph2',
should be `PHILIPPINES` (typo)

2023-01-10 23:55 UTC, xEcEz commented
No worries! Done.

2023-01-13 19:57 UTC, bcho04 approved these changes
Looks good!

2023-01-13 19:57 UTC, merged

2023-01-16 11:25 UTC, xEcEz commented
Are you sure you've built the package before the `0.6.1` release? Looks like the changes are in the source code, but not in the distributed version.

2023-01-19 13:36 UTC, xEcEz commented
Did you have a chance to look into this?

2024-04-10 15:11 UTC, Kennn-dev commented
Yeah , LeagueRegion enum in package still not update :(